import type { CharacterStats } from './types';

export const CHARACTERS: Record<string, CharacterStats> = {
  RAMA: {
    id: 'RAMA',
    name: 'Rama',
    title: 'Maryada Purushottam',
    tier: 4,
    maxHp: 5000,
    hp: 5000,
    maxMana: 3000,
    mana: 3000,
    attack: 450,
    defense: 380,
    speed: 340,
    dharmaScore: 100,
    astras: ['BRAHMASTRA', 'AGNEYASTRA', 'VARUNASTRA', 'VAYAVYASTRA'],
    isPlayable: true,
    description: 'Prince of Ayodhya. The Supreme Person of Boundaries. Master of the Sharanga bow and divine Astras.'
  },
  HANUMAN: {
    id: 'HANUMAN',
    name: 'Hanuman',
    title: 'Pavanputra Hanuman',
    tier: 4,
    maxHp: 8000,
    hp: 8000,
    maxMana: 4000,
    mana: 4000,
    attack: 600,
    defense: 500,
    speed: 600,
    dharmaScore: 100,
    astras: ['BAJRANG_ASTRA'],
    siddhis: ['ANIMA', 'MAHIMA', 'GARIMA', 'LAGHIMA', 'PRAPTI', 'PRAKAMYA', 'ISHATVA', 'VASITVA'],
    isPlayable: true,
    description: 'Son of Vayu. Devotee of Rama. Master of the Eight Siddhis. Can change size at will and leap across oceans.'
  },
  LAKSHMANA: {
    id: 'LAKSHMANA',
    name: 'Lakshmana',
    title: 'Saumitri',
    tier: 3,
    maxHp: 3500,
    hp: 3500,
    maxMana: 1500,
    mana: 1500,
    attack: 380,
    defense: 420,
    speed: 320,
    dharmaScore: 95,
    astras: ['NARAYAN_ASTRA', 'MOHINI_ASTRA'],
    isPlayable: true,
    description: 'Prince of Ayodhya. Devoted younger brother of Rama. Known for 12 years without sleep, can pierce Maya illusions.'
  },
  SITA: {
    id: 'SITA',
    name: 'Sita',
    title: 'Daughter of Janaka',
    tier: 3,
    maxHp: 2000,
    hp: 2000,
    maxMana: 5000,
    mana: 5000,
    attack: 200,
    defense: 250,
    speed: 280,
    dharmaScore: 100,
    astras: [],
    isPlayable: false,
    description: 'Princess of Mithila. Her unwavering purity is a divine force in itself.'
  },
  RAVANA: {
    id: 'RAVANA',
    name: 'Ravana',
    title: 'King of Lanka, Dashanan',
    tier: 4,
    maxHp: 10000,
    hp: 10000,
    maxMana: 6000,
    mana: 6000,
    attack: 700,
    defense: 600,
    speed: 400,
    dharmaScore: -80,
    astras: ['PASHUPATASTRA', 'BRAHMASTRA', 'AGNEYASTRA'],
    isPlayable: false,
    description: 'Ten-headed demon king. Great devotee of Shiva. Heads regenerate unless struck at the navel with Brahmastra.'
  },
  TATAKA: {
    id: 'TATAKA',
    name: 'Tataka',
    title: 'Forest Demoness',
    tier: 2,
    maxHp: 1200,
    hp: 1200,
    maxMana: 400,
    mana: 400,
    attack: 280,
    defense: 200,
    speed: 180,
    dharmaScore: -60,
    astras: [],
    isPlayable: false,
    description: 'Fearsome demoness who terrorizes Vishwamitra\'s hermitage. First major boss encounter.'
  },
  KHARA: {
    id: 'KHARA',
    name: 'Khara',
    title: 'Commander of Janasthana',
    tier: 2,
    maxHp: 2400,
    hp: 2400,
    maxMana: 600,
    mana: 600,
    attack: 320,
    defense: 280,
    speed: 240,
    dharmaScore: -50,
    astras: [],
    isPlayable: false,
    description: 'Ravana\'s cousin. Commands 14,000 rakshasas. Sent to avenge Surpanakha.'
  },
  DUSHANA: {
    id: 'DUSHANA',
    name: 'Dushana',
    title: 'Khara\'s General',
    tier: 2,
    maxHp: 1800,
    hp: 1800,
    maxMana: 500,
    mana: 500,
    attack: 300,
    defense: 250,
    speed: 220,
    dharmaScore: -50,
    astras: [],
    isPlayable: false,
    description: 'Khara\'s faithful general. Falls alongside his commander in battle.'
  },
  VALI: {
    id: 'VALI',
    name: 'Vali',
    title: 'King of Kishkindha',
    tier: 3,
    maxHp: 5000,
    hp: 5000,
    maxMana: 1000,
    mana: 1000,
    attack: 520,
    defense: 480,
    speed: 380,
    dharmaScore: -20,
    astras: [],
    isPlayable: false,
    description: 'The invincible monkey king who halves his opponent\'s strength. Cannot be defeated in open combat. Must be slain from concealment.'
  },
  INDRAJIT: {
    id: 'INDRAJIT',
    name: 'Indrajit',
    title: 'Meghnad, Conqueror of Indra',
    tier: 3,
    maxHp: 4200,
    hp: 4200,
    maxMana: 3000,
    mana: 3000,
    attack: 480,
    defense: 380,
    speed: 420,
    dharmaScore: -60,
    astras: ['BRAHMASTRA', 'NAGASTRA', 'PASHUPATASTRA'],
    isPlayable: false,
    description: 'Ravana\'s greatest son. Master of illusion. Invisible during battle - only Lakshmana\'s sleepless eyes can pierce his Maya.'
  },
  KUMBHAKARNA: {
    id: 'KUMBHAKARNA',
    name: 'Kumbhakarna',
    title: 'The Giant of Lanka',
    tier: 4,
    maxHp: 12000,
    hp: 12000,
    maxMana: 500,
    mana: 500,
    attack: 800,
    defense: 700,
    speed: 150,
    dharmaScore: -40,
    astras: [],
    isPlayable: false,
    description: 'Ravana\'s giant brother. Sleeps for 6 months at a time. Requires the entire Vanara Sena to pin him down before delivering the killing blow.'
  },
  MARICHA: {
    id: 'MARICHA',
    name: 'Maricha',
    title: 'The Golden Deer',
    tier: 2,
    maxHp: 800,
    hp: 800,
    maxMana: 2000,
    mana: 2000,
    attack: 0,
    defense: 0,
    speed: 500,
    dharmaScore: -30,
    astras: [],
    isPlayable: false,
    description: 'A rakshasa sorcerer who transforms into a golden deer. His role is deception, luring Rama away so Ravana can abduct Sita.'
  }
};
